-- Postal Locale File
-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/postal/localization/

local AL3 = LibStub("AceLocale-3.0")
local debug = false
--@debug@
debug = true
--@end-debug@

local L = AL3:NewLocale("Postal", "enUS", true, debug)
if L then
--@localization(locale="enUS", format="lua_additive_table", same-key-is-true=true, table-name="L")@
if GetLocale() == "enUS" or GetLocale() == "enGB" then return end
end

local L = AL3:NewLocale("Postal", "deDE")
if L then
--@localization(locale="deDE", format="lua_additive_table", table-name="L", handle-unlocalized="comment")@
return
end

local L = AL3:NewLocale("Postal", "esES") or AL3:NewLocale("Postal", "esMX")
if L then
--@localization(locale="esES", format="lua_additive_table", table-name="L", handle-unlocalized="comment")@
return
end

local L = AL3:NewLocale("Postal", "frFR")
if L then
--@localization(locale="frFR", format="lua_additive_table", table-name="L", handle-unlocalized="comment")@
return
end

local L = AL3:NewLocale("Postal", "koKR")
if L then
--@localization(locale="koKR", format="lua_additive_table", table-name="L", handle-unlocalized="comment")@
return
end

local L = AL3:NewLocale("Postal", "ruRU")
if L then
--@localization(locale="ruRU", format="lua_additive_table", table-name="L", handle-unlocalized="comment")@
return
end

local L = AL3:NewLocale("Postal", "zhCN")
if L then
--@localization(locale="zhCN", format="lua_additive_table", table-name="L", handle-unlocalized="comment")@
return
end

local L = AL3:NewLocale("Postal", "zhTW")
if L then
--@localization(locale="zhTW", format="lua_additive_table", table-name="L", handle-unlocalized="comment")@
return
end

local L = AL3:NewLocale("Postal", "ptBR")
if L then
--@localization(locale="ptBR", format="lua_additive_table", table-name="L", handle-unlocalized="comment")@
return
end

local L = AL3:NewLocale("Postal", "itIT")
if L then
--@localization(locale="itIT", format="lua_additive_table", table-name="L", handle-unlocalized="comment")@
return
end
